export const IconNameList = [
	"backArrow_grey130",
	"bookmark_grey60",
	"bookmark_primaryBrand",
	"cafeteria_primaryDarker",
	"campaign_primaryDarker",
	"check_grey60",
	"check_primaryBrand",
	"checkCircle_grey60",
	"checkCircle_primaryBrand",
	"clear_grey90",
	"forwardArrow_grey90",
	"forwardArrow_grey130",
	//
	"library_primaryDarker",
	"menu_grey190",
	"menu_primaryBrand",
	"openInNew_primaryBrand",
	"person_grey190",
	"person_primaryBrand",
	"person_white",
	"studentId_grey190",
	"studentId_primaryBrand",
	"time_primaryBrand",
	"uoslife_white",
] as const;

// const IconsRequireObject: IconsRequireObjectType = {
// 	uoslife_white: require("../images/icons/uoslife_white.png"),
// 	cafeteria_primaryDarker: require("../images/icons/cafeteria_primaryDarker.png"),
// 	library_primaryDarker: require("../images/icons/library_primaryDarker.png"),
// 	campaign_primaryDarker: require("../images/icons/campaign_primaryDarker.png"),
// 	utility_primaryBrand: require("../images/icons/utility_primaryBrand.png"),
// 	utility_grey130: require("../images/icons/utility_grey130.png"),
// 	studentId_primaryBrand: require("../images/icons/studentId_primaryBrand.png"),
// 	studentId_grey130: require("../images/icons/studentId_grey130.png"),
// 	person_primaryBrand: require("../images/icons/person_primaryBrand.png"),
// 	person_grey130: require("../images/icons/person_grey130.png"),
// 	person_white: require("../images/icons/person_white.png"),
// 	openInNew_primaryBrand: require("../images/icons/openInNew_primaryBrand.png"),
// 	timer_primaryBrand: require("../images/icons/timer_primaryBrand.png"),
// 	bookmark_primaryBrand: require("../images/icons/bookmark_primaryBrand.png"),
// 	bookmark_grey60: require("../images/icons/bookmark_grey60.png"),
// };

// export default IconsRequireObject;
